[font]
normal = { family = "Iosevka Term SS11" }
size = 20.0

[keyboard]
bindings = [
    { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_light.toml"
]
